### ISSUE TITLE
Code Release Date

### ISSUE THREAD

**Issue by cmsc426** [zju3dv/deltar#1]
Hi,
Congratulations on the amazing work! When do you plan to release the code in public?

**Comment by eugenelyj** [comment]
Hi, I plan to release the evaluation code and the data at the end of this month or early next month, and release the training script after cvpr23 submission.

**Comment by Lilyo** [comment]
Hi @eugenelyj,

Thanks for your excellent work! I would like to know how to generate training data containing L5 signal, could you please release the generation function for NYU dataset in advance?

**Comment by eugenelyj** [comment]
@Lilyo Sorry for the late reply. An example code for simulating L5 signals is here:
https://gist.github.com/eugenelyj/769f19a9450ea0316a5995aa79692bef.

I will work on code release from next week.

**Comment by noobtoob4lyfe** [comment]
I just learned of this project today.  Fantastic work!  looking forward to trying example code.  Any updates to a release date?  Thanks!

**Comment by eugenelyj** [comment]
@noobtoob4lyfe Sorry, i was busy on another project last two weeks. Will come back soon.

**Comment by Lilyo** [comment]
@eugenelyj, 
I can imagine how packed your other projects must be, but we're still looking forward to your code releasing, maybe release whole model structure in advance for us ?

**Comment by microboym** [comment]
@eugenelyj 
I just read your paper and got shocked by your fantastic work! I'm planing to learn your method more carefully. Will the code and data be released recently?

**Comment by eugenelyj** [comment]
@microboym 
I'm trying to release this week.

**Comment by eugenelyj** [comment]
Sorry for the delay. I have released eval code, data and pretrained model. Still working on the README and training script.
