### ISSUE TITLE
关于选取NYUdepth数据集的获取

### ISSUE THREAD

**Issue by illuosion** [zju3dv/deltar#14]
大佬的工作很棒！我想请教一下怎么获取论文中所述选出的数据集（可以在kaggle上获得吗），我想要进一步搭建自己的数据集以供训练，谢谢！！！

**Comment by eugenelyj** [comment]
你好，感谢对我们工作的关注。
nyu的网站在这：https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html

**Comment by illuosion** [comment]
> 你好，感谢对我们工作的关注。 nyu的网站在这：https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html

谢谢您的回复，不过我注意到在您文中提及的是24K的子集，请问这是随意选取的吗

**Comment by eugenelyj** [comment]
> > 你好，感谢对我们工作的关注。 nyu的网站在这：https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html
> 
> 谢谢您的回复，不过我注意到在您文中提及的是24K的子集，请问这是随意选取的吗

我们是follow Adabins和BTS这两篇paper来使用NYU的。
BTS的[paper](https://arxiv.org/pdf/1907.10326.pdf)里写他做了一下处理得到了这个24K的子集。
如果我没记错的话，我应该是从[这里](https://github.com/cleinc/bts/tree/master/pytorch)下载的。

**Comment by illuosion** [comment]
万分感谢您的回复，这对我帮助很大。

**Comment by eugenelyj** [comment]
不客气。
