### ISSUE TITLE
关于参数--simu_max_distance

### ISSUE THREAD

**Issue by ShadowBbBb** [zju3dv/deltar#15]
感谢您的工作！
我在实验过程中发现，构建直方图的部分使用了参数--simu_max_distance=4，但是--max_depth=10。
想问一下为什么要这样设置，以及这两个参数的关系。

**Comment by eugenelyj** [comment]
@ShadowBbBb 你好，第一个参数是模拟轻量级ToF的深度测距范围，4米是我们使用的型号的最远测距范围；10米是算法的最远范围，因为我们follow adabins用了一样的深度输出的形式，所以需要设置一个范围。

**Comment by ShadowBbBb** [comment]
感谢回复！
还有一个小问题，论文中Fig4的PointNet包括四个层级，对应四次fusion操作，但是代码中似乎只有3次fusion？

**Comment by eugenelyj** [comment]
> 感谢回复！ 还有一个小问题，论文中Fig4的PointNet包括四个层级，对应四次fusion操作，但是代码中似乎只有3次fusion？

是的，现在release的代码是我们升级后的，速度更快并且性能也有些提升，我在这个[issue](https://github.com/zju3dv/deltar/issues/7#issuecomment-1505244569)提到过。然后我考虑尽快把这个版本的arxiv放出来吧。

**Comment by ShadowBbBb** [comment]
非常感谢！
