### ISSUE TITLE
补充材料的下载链接失效的问题

### ISSUE THREAD

**Issue by Lan1eve** [zju3dv/deltar#16]
感谢大佬的工作！
项目主页中的补充材料下载链接失效了，请问作者可以提供一个新的下载链接吗？
非常感谢！！

**Comment by eugenelyj** [comment]
> 感谢大佬的工作！ 项目主页中的补充材料下载链接失效了，请问作者可以提供一个新的下载链接吗？ 非常感谢！！

你说的是这个[链接](http://www.cad.zju.edu.cn/home/gfzhang/papers/deltar/supp.pdf)吗？奇怪，我用手机然后正常的4G网络可以访问。

**Comment by Lan1eve** [comment]
之前在电脑上一直没下成功，现在用手机4G网络下下来了，非常感谢!

**Comment by eugenelyj** [comment]
好吧，可能是你的电脑代理设置导致的？因为我这个托管在学校的服务器了，可能对流量有一些设置，不太清楚。
