### ISSUE TITLE
discretize the distribution by sampling depth hypotheses

### ISSUE THREAD

**Issue by sunyuan789** [zju3dv/deltar#2]
Hello professor, your work has really enlighten me. However, I have some questions. In your paper 4.1 chapter, you write "discretize the distribution by sampling depth hypotheses". Could you please tell me what does that mean or how did that? Thank you!

**Comment by eugenelyj** [comment]
@sunyuan789 Hi, here we mean we sample some value from the distribution

**Comment by sunyuan789** [comment]
Thank you! I have learned something. I'm looking forward to your code~
