### ISSUE TITLE
How to compute the relative rotation and translation between the color camera and the L5 sensor？

### ISSUE THREAD

**Issue by a304628356** [zju3dv/deltar#4]
Hello，your work is excellent and inspiring. I want to build a system to build dataset likes yours. Will you released the code of compute the relative rotation and translation between the color camera and the L5 sensor? thanks

**Comment by eugenelyj** [comment]
@a304628356 Hi, the calibration code is a bit complicated and we do not plan to release the code up to now.
You can leave an email and i will send you the project.

**Comment by np-csu** [comment]
Hi, my email is nipan1988(at)gmail.com, could you please send me one copy of this project, thanks very much! @eugenelyj

**Comment by wdh234** [comment]
大佬，校准项目代码能发给一份吗？1120353556@qq.com。谢谢！

**Comment by gnsshr** [comment]
Hi eugenelyj,
Thanks for sharing your great work and code release.
Could I also get your project including RGB + ToF calibration?
My email address is gnsshr@gmail.com.

Thanks in advance again!

**Comment by gnsshr** [comment]
Hi eugenelyj,
Could you also point out where the calibration parameters are injected in the source code?
Thanks!

**Comment by eugenelyj** [comment]
@gnsshr the intrinsic of RGB image is hard coded in the ZJUL5.py. We pre-process the ZJUL5 data and aligh the L5' data with RGB image so we don't need the extrinsic parameter anymore.

**Comment by gnsshr** [comment]
@eugenelyj Thanks for your quick guide!
I believe that self.K_list is the hard coded intrinsics you mentioned including focal length and principal point of RGB.
Thanks!

**Comment by yashveerjain** [comment]
Congratulations, on your fantastic work, really inspiring. And I am also interested in the project copy, please send me one copy, my email address is yashveerjain321@gmail.com.
Thanks!

**Comment by WonJunPark** [comment]
Can I get calibration code? dnjswns2280@naver.com
And I wonder what the motherboard used.

**Comment by chahatdeep** [comment]
Could you please send the calibration code to chahat@umd.edu?

**Comment by eugenelyj** [comment]
Thank you for your attention. I plan to publish the calibration code in a new repo.

**Comment by eugenelyj** [comment]
@WonJunPark We use raspberry pi 4b. You can find a document named "VL53L5CX_Linux_Getting_started_with_Rpi.pdf" if you download the VL53L5CX linux driver from the [st-community](https://community.st.com).

**Comment by puyiwen** [comment]
> 感谢您的关注。我计划在新的存储库中发布校准代码。

Thank you for your great work! I would like to test the generalization of your work in my own indoor scene, L5 and RGB calibration codes are required, could you please send the calibration code to my email? My email is **puyiwen01230123@gmail.com** Thank you very much!!

**Comment by puyiwen** [comment]
> Hi, my email is nipan1988(at)gmail.com, could you please send me one copy of this project, thanks very much! @eugenelyj

Hi, have you got the calibration codes?

**Comment by np-csu** [comment]
> > Hi, my email is nipan1988(at)gmail.com, could you please send me one copy of this project, thanks very much! @eugenelyj
> 
> Hi, have you got the calibration codes?

not yet

**Comment by eugenelyj** [comment]
Sorry for the delay. I have put the related code in [this repo](https://github.com/eugenelyj/Calib_DELTAR).
