### ISSUE TITLE
开源工程

### ISSUE THREAD

**Issue by wdh234** [zju3dv/deltar#5]
大佬，你的工作太有意义了，请问你什么时候开源代码呢？

**Comment by eugenelyj** [comment]
不好意思啊弄得有点晚。现在把evaluate，data和pretrained先放出来了。我会再接着完善readme并且把training code也接着放出来。

**Comment by lycqu** [comment]
大佬，可以考虑把数据上传一份到百度网盘上么？

**Comment by wdh234** [comment]
> 

谢谢大佬！

**Comment by eugenelyj** [comment]
@lycqu https://pan.baidu.com/s/13qoVoZejiRzmoJGkFJdh0w?pwd=1i11
