### ISSUE TITLE
关于模型fine-tune的问题

### ISSUE THREAD

**Issue by puyiwen** [zju3dv/deltar#6]
大佬，你的工作真的太有意义了。我有个疑问，我看了论文注意到最后是在ZJU-L5数据上面进行fine-tune，这个数据量是非常小的，总共才1000多张吧，这么小的数据量fine-tune的时候不会过拟合吗？因为我目前也做了单目深度估计模型的fine-tune，我混合了几个公开数据大概20多万张，训练了一个模型，然后加载我训练好的模型在我自己采集的2000多张数据上面fine-tune的时候过拟合了。我不清楚是由于数据量太小过拟合了，还是其他什么原因。如果可以的话，可以多说一些fine-tune的细节吗？比如一些fine-tune的示例代码。

**Comment by eugenelyj** [comment]
@puyiwen 我们fine-tune的时候是把500多张的那个训练数据和nyu上两万多张的数据混合后一块训的，另外需要把小的这个数据重复一下来平衡两个混合数据的比例，我们是参考[raft](https://github.com/princeton-vl/RAFT/blob/master/core/datasets.py#L221)里的做法的

**Comment by puyiwen** [comment]
@eugenelyj 非常感谢您的回复，我应该是明白了
