### ISSUE TITLE
关于tof数据问题

### ISSUE THREAD

**Issue by puyiwen** [zju3dv/deltar#8]
大佬您好，我发现训练时候模拟的tof数据是像素相对于相机平面的距离，但是真实tof传出来的数据是像素相对于相机中心的距离，您在处理tof数据的时候是将原始tof数据转换成了相对于相机平面的距离吗？

**Comment by eugenelyj** [comment]
@puyiwen hi，一般我们说的深度都是指到相机平面的距离，所以训练的时候也是这样的语义，并且一般深度传感器传回给我们的信息，也是已经转换到这样的语义的了，包括realsense、L5等等。但是，我印象中，处理L5数据的时候因为我们标定算法需要的语义是三维空间中的距离，所以我们试过将其从到相机平面的距离（一般就是z方向上的距离）转回到三维空间中的距离（也就是x,y,z一块算的距离），但是标定的结果和直接将其看做是三维空间距离没什么差别，我们估计是因为传感器精度的问题导致的。
