### ISSUE TITLE
cannot make the same result as the repo example image

### ISSUE THREAD

**Issue by jhoon-kim** [zju3dv/deltar#9]
hello,
first, thanks for sharing your work

i attempted to reproduce the same result as the example image from readme.md
but there is a big difference in quality

i used the provided weight, data, and config
should i use different parameters to reproduce the result?

i attatched the result that i made
![demo_cut](https://github.com/zju3dv/deltar/assets/61264455/ffa5df2a-dadb-4327-832b-20105c3cf5ac)
please understand that the file is compressed due to file size issue

**Comment by CHANGXU12** [comment]
I have the same blurry depth, too. Waiting for the reply. 
I found timm downloads tf_efficientnetv2_b3 checkpoints(tf_efficientnetv2_b3-57773f13.pth) at first. 
Is it different from what you used in training?

**Comment by jhoon-kim** [comment]
> I have the same blurry depth, too. Waiting for the reply. I found timm downloads tf_efficientnetv2_b3 checkpoints(tf_efficientnetv2_b3-57773f13.pth) at first. Is it different from what you used in training?

i didn't train the model, used the given weight
i couldn't find the file that you said, there is "model.safetensors"
![image](https://github.com/zju3dv/deltar/assets/61264455/3660a9d2-64bb-4ec2-af67-c0326b2df689)

windows 10
torch                   1.13.1+cu117
timm                    0.9.2

what version of timm do you use?

**Comment by eugenelyj** [comment]
I am using: 1) torch 1.12.0+cu113 and 2) timm 0.5.4
@CHANGXU12 @jhoon-kim Could you switch to these version and try agian?

**Comment by jhoon-kim** [comment]
> I am using: 1) torch 1.12.0+cu113 and 2) timm 0.5.4 @CHANGXU12 @jhoon-kim Could you switch to these version and try agian?

I reinstalled that you said, now I am getting the similar results
thanks!
can you provide the "requirements.txt"?

**Comment by eugenelyj** [comment]
@jhoon-kim Sure, i will update the readme. Thanks for the suggestions!

**Comment by eugenelyj** [comment]
I have updated the installation tutorial. Feel free to ask when you have new questions.
